### ISSUE TITLE
No Audio passed to jackaudio-server

### ISSUE THREAD

**Issue by MariusLuding** [marcan/rtlmic#3]
The rtlmic client registers at the jackaudio-server but no sound is played.  
(checked with "jack_lsp -c" output is: 
```
system:capture_1
system:capture_2
system:playback_1
system:playback_2
rtlmic:channel_1
```
with sndfile-jackplay on an audiofile it displays:
```
system:capture_1
system:capture_2
system:playback_1
   jackplay:out_1
system:playback_2
   jackplay:out_2
jackplay:out_1
   system:playback_1
jackplay:out_2
   system:playback_2
```
)
Setup is running with "rtlmic 637000000 -v -b 2048" (other wise getting a lot of ring buffer underrun errors).
The microphone used for this is a sennheiser skm2000 series.
I am new to jackaudio, so this approach of testing/troubleshooting might be unsuitable altogether.

**Comment by marcan** [comment]
JACK clients intended to play back audio will often auto-connect to the default system ports, but not all do. rtlmic is not just intended to be used for direct playback through the output (e.g. you might want to connect it to other filters or use it as input to a recording application), so it doesn't.

To loop it back to the system output, do something like:
```
$ jack_connect rtlmic:channel_1 system:playback_1
$ jack_connect rtlmic:channel_1 system:playback_2
```

You can use a tool like QJackCtl to set up a patchbay that automatically makes these connections for you whenever you run the relevant applications.
