### ISSUE TITLE
Fudge back to Broadcast FM

### ISSUE THREAD

**Issue by Baggypants** [marcan/rtlmic#4]
Would it be possible to fudge this back to picking up wideband FM? I'd like to use it in another project that uses jack audio.

**Comment by marcan** [comment]
It won't do stereo decoding for you, but I don't see why it wouldn't work in mono. Haven't tested it myself, but try something like -e 1 to turn off the compander and play with the squelch settings. The default pre-emphasis is suitable for FM broadcast in the Americas; try -M 50 for most the rest of the world.

**Comment by Baggypants** [comment]
it works! `rtlmic -e1 -M 50 97700000` got me 97.7MHz a radio station that's here.
